### ISSUE TITLE
Graphite stops displaying data

### ISSUE THREAD

**Issue by garep** [graphite-project/graphite-web#1682]
I've been noticing the following happening with my carbon-cache machines having the following:
```
2016-09-06_14:15:16.62785   File "/opt/graphite/lib/carbon/events.py", line 32, in <lambda>
2016-09-06_14:15:16.62785     cacheFull.addHandler(lambda: carbon.instrumentation.increment('cache.overflow'))
2016-09-06_14:15:16.62786 exceptions.NameError: global name 'carbon' is not defined
2016-09-06_14:15:16.62786
2016-09-06_14:15:16.62788 06/09/2016 14:15:16 :: [clients] CarbonClientFactory(127.0.0.1:2034:b) send queue is full (1000 datapoints)
2016-09-06_14:15:16.64483 06/09/2016 14:15:16 :: [clients] CarbonClientProtocol(127.0.0.1:2024:a) send queue has space available
2016-09-06_14:15:16.64732 06/09/2016 14:15:16 :: [clients] CarbonClientProtocol(127.0.0.1:2034:b) send queue has space available
2016-09-06_14:15:16.73352 06/09/2016 14:15:16 :: [console] Exception in cacheFull event handler: args=() kwargs={}
2016-09-06_14:15:16.73356 Traceback (most recent call last):
2016-09-06_14:15:16.73357   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 362, in callback
2016-09-06_14:15:16.73358     self._startRunCallbacks(result)
2016-09-06_14:15:16.73359   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 458, in _startRunCallbacks
2016-09-06_14:15:16.73359     self._runCallbacks()
2016-09-06_14:15:16.73360   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 545, in _runCallbacks
2016-09-06_14:15:16.73360     current.result = callback(current.result, *args, **kw)
2016-09-06_14:15:16.73361   File "/opt/graphite/lib/carbon/client.py", line 114, in queueFullCallback
2016-09-06_14:15:16.73361     events.cacheFull()
2016-09-06_14:15:16.73362 --- <exception caught here> ---
2016-09-06_14:15:16.73362   File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
```

Restarting the carbon-cache-default process fixes the issue.  Any ideas on a fix?

Thanks,
Gary

**Comment by obfuscurity** [comment]
You have a couple things going on here. The exception `global name 'carbon' is not defined` is a bug that was fixed in https://github.com/graphite-project/carbon/commit/6aeb5b94274a36f41a2c32a74753a3d05b0cacc2. You should apply that fix or upgrade to 0.9.15.

The log is also telling you that your carbon-cache has hit `MAX_CACHE_SIZE`. That is to say, your cache is holding the maximum number of datapoints allowed. Short-term you can increase the `MAX_CACHE_SIZE`, but you should plan on scaling your node(s) vertically (more caches + relay) or horizontally (more nodes).

**Comment by garep** [comment]
Thanks!

**Comment by obfuscurity** [comment]
My pleasure!

**Comment by garep** [comment]
@obfuscurity we have the following setting:
MAX_CACHE_SIZE = inf 

Still seeing this issue.

**Comment by obfuscurity** [comment]
There's no way you should be seeing that log entry with `MAX_CACHE_SIZE = inf`. Your system is lying to you; either you're not running the settings _you think_ you are, or something else is going on.

https://github.com/graphite-project/carbon/blob/0.9.14/lib/carbon/cache.py#L46-L53

**Comment by garep** [comment]
Got it, here is our entire config
`default["ges-graphite"]["carbonrelay_role"] = "carbonrelay"
default["ges-graphite"]["datanode_role"] = "carboncache"
default["ges-graphite"]["webapi_role"] = "graphiteweb"

default["graphite"]["install_type"] = "package"
default["graphite"]["version"] = "0.9.15"
default["graphite"]["twisted_version"] = "11.1"
default["graphite"]["user"]         = "graphite"
default["graphite"]["group"]        = "www-data"
default["graphite"]["user_account"] = "graphite"
default["graphite"]["group_account"] = "www-data"
default["graphite"]["base_dir"]     = "/opt/graphite"
default["graphite"]["doc_dir"]      = "/opt/graphite/webapp"
default["graphite"]["storage_dir"]  = "/opt/graphite/storage"
default["graphite"]["listen_address"]  = "0.0.0.0"
default["graphite"]["listen_port"]  = 80
default["graphite"]["ssl"]["enabled"] = false

default["graphite"]["uwsgi"]["service_type"] = 'runit'
default["graphite"]["uwsgi"]["socket_permissions"] = 777
default["graphite"]["uwsgi"]["port"] = 8080

default["graphite"]["web"]["memcached_hosts"] = []

default["graphite"]["carbon_cache"]["default"]["config"]["pickle_receiver_port"] = 2004

default["graphite"]["carbon_cache"]["a"]["config"]["enable_logrotation"] = true
default["graphite"]["carbon_cache"]["a"]["config"]["max_cache_size"] = "inf"
default["graphite"]["carbon_cache"]["a"]["config"]["max_updates_per_second"] = 500
default["graphite"]["carbon_cache"]["a"]["config"]["max_creates_per_minute"] = 50
default["graphite"]["carbon_cache"]["a"]["config"]["line_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["a"]["config"]["line_receiver_port"] = 2023
default["graphite"]["carbon_cache"]["a"]["config"]["udp_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["a"]["config"]["udp_receiver_port"] = 2023
default["graphite"]["carbon_cache"]["a"]["config"]["pickle_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["a"]["config"]["pickle_receiver_port"] = 2024
default["graphite"]["carbon_cache"]["a"]["config"]["enable_udp_listener"] = true
default["graphite"]["carbon_cache"]["a"]["config"]["cache_query_port"] = 7022
default["graphite"]["carbon_cache"]["a"]["config"]["cache_write_strategy"] = "sorted"
default["graphite"]["carbon_cache"]["a"]["config"]["use_flow_control"] = true
default["graphite"]["carbon_cache"]["a"]["config"]["log_updates"] = false
default["graphite"]["carbon_cache"]["a"]["config"]["log_cache_hits"] = false
default["graphite"]["carbon_cache"]["a"]["config"]["whisper_autoflush"] = false

default["graphite"]["carbon_cache"]["b"]["config"]["enable_logrotation"] = true
default["graphite"]["carbon_cache"]["b"]["config"]["max_cache_size"] = "inf"
default["graphite"]["carbon_cache"]["b"]["config"]["max_updates_per_second"] = 500
default["graphite"]["carbon_cache"]["b"]["config"]["max_creates_per_minute"] = 50
default["graphite"]["carbon_cache"]["b"]["config"]["line_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["b"]["config"]["line_receiver_port"] = 2033
default["graphite"]["carbon_cache"]["b"]["config"]["udp_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["b"]["config"]["udp_receiver_port"] = 2033
default["graphite"]["carbon_cache"]["b"]["config"]["pickle_receiver_interface"] = "127.0.0.1"
default["graphite"]["carbon_cache"]["b"]["config"]["pickle_receiver_port"] = 2034
default["graphite"]["carbon_cache"]["b"]["config"]["enable_udp_listener"] = true
default["graphite"]["carbon_cache"]["b"]["config"]["cache_query_port"] = 7032
default["graphite"]["carbon_cache"]["b"]["config"]["cache_write_strategy"] = "sorted"
default["graphite"]["carbon_cache"]["b"]["config"]["use_flow_control"] = true
default["graphite"]["carbon_cache"]["b"]["config"]["log_updates"] = false
default["graphite"]["carbon_cache"]["b"]["config"]["log_cache_hits"] = false
default["graphite"]["carbon_cache"]["b"]["config"]["whisper_autoflush"] = false

default["graphite"]["carbon_relay"]["config"]["line_receiver_interface"] = "0.0.0.0"
default["graphite"]["carbon_relay"]["config"]["line_receiver_port"] = 2003
default["graphite"]["carbon_relay"]["config"]["pickle_receiver_interface"] = "0.0.0.0"
default["graphite"]["carbon_relay"]["config"]["pickle_receiver_port"] = 2004
default["graphite"]["carbon_relay"]["config"]["relay_method"] = "consistent-hashing"
default["graphite"]["carbon_relay"]["config"]["replication_factor"] = 3
default["graphite"]["carbon_relay"]["config"]["pattern"] = ".*"
default["graphite"]["carbon_relay"]["config"]["max_queue_size"] = 3000000

default["graphite"]["carbon_servers"] = []
default["graphite"]["cluster_servers"] = []
default["graphite"]["carbonlink_hosts"] = []
default["graphite"]["databases"] = {
    'default' => {
        'NAME' => '/opt/graphite/storage/graphite.db',
        'ENGINE' => 'django.db.backends.sqlite3',
        'USER' => '',
        'PASSWORD' => '',
        'HOST' => '',
        'PORT' => ''
    }
}`

Everything ok here?

**Comment by obfuscurity** [comment]
It looks right but that's your CM config, not your generated `carbon.conf`. I have no idea if this has actually been applied to your running system and that the `carbon-cache` processes have been restarted.

P.S. Note that I updated your comment to use triple backticks for code blocks, please use these in the future.

P.P.S. Also note that it's a good practice to set your `MAX_CACHE_SIZE` to a non-`inf` value. I touch on the reasons why [in this blog post](http://obfuscurity.com/2016/08/Benchmarking-Carbon-and-Whisper-on-AWS) as well as the Scaling chapter of [this book](http://shop.oreilly.com/product/0636920035794.do). Long story short, Carbon will only perform batch writes effectively when you limit the cache size. It's fine to start with `inf` but you should observe your cache size (`carbon.agents.*.cache.size`) and then set `MAX_CACHE_SIZE` (and `MAX_UPDATES_PER_SECOND`) to a reasonable value.

**Comment by garep** [comment]
@obfuscurity thanks, will take a look at those params. Appreciate the quick response!

**Comment by obfuscurity** [comment]
No problem!
